import { Component, OnInit } from '@angular/core';
import { PopoverController } from '@ionic/angular';

@Component({
  selector: 'app-search-popover',
  templateUrl: './search-popover.component.html',
  styleUrls: ['./search-popover.component.scss'],
})
export class SearchPopoverComponent implements OnInit {

  columnData = [
    {name:'no',displayName:'No.', sorting:false, sortingData:"dont know as of now"},
    {name:'sessionName', displayName:'Session name',sorting:true, sortingData:"dont know as of now"},
    {name:'type', displayName:'Type',sorting:false, sortingData:"dont know as of now"},
    {name:'mentor',displayName:'Mentor', sorting:false, sortingData:"dont know as of now"},
    {name:'date',displayName:'Date', sorting:true, sortingData:"dont know as of now"},
    {name:'time', displayName:'Time',sorting:true, sortingData:"dont know as of now"},
    {name:'duration',displayName:'Duration(min)', sorting:true, sortingData:"dont know as of now"},
    {name:'menteeCount', displayName:'Mentee count',sorting:false, sortingData:"dont know as of now"},
    {name:'status',displayName:'Status', sorting:false, sortingData:"dont know as of now"},
    {name:'action', displayName:'Actions',sorting:false, sortingData:"dont know as of now"},
]
  tableData: { no: number; sessionName: string; type: string; mentor: string; date: string; time: string; duration: number; menteeCount: number; status: string; action: string; }[];
  constructor(private popoverController: PopoverController) { }

  ngOnInit() {
    this.tableData = [
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      }, { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
       { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      }, { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 10, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
       
      // Add more data as needed
     
    ];
  }

  closePopover(){
    this.popoverController.dismiss();
  }

}
