export const environment = {
	production: true ,
	name: window['env' as any]['name' as any] as unknown as string,
	baseUrl: window['env' as any]['baseUrl'] as unknown as string,
	sqliteDBName: window['env' as any]['sqliteDBName' as any]  as unknown as string,
	deepLinkUrl: window['env' as any]['deepLinkUrl']  as unknown as string,
	privacyPolicyUrl: window['env' as any]['privacyPolicyUrl' as any]  as unknown as string,
	termsOfServiceUrl: window['env' as any]['termsOfServiceUrl' as any]  as unknown as string,
	recaptchaSiteKey: window['env' as any]['recaptchaSiteKey' as any]  as unknown as string,
	recaptchaSiteKeyOld: window['env' as any]['recaptchaSiteKeyOld']  as unknown as string,
	restictedPages: window['env' as any]['restictedPages'],
	unauthorizedRedirectUrl: window['env' as any]['unauthorizedRedirectUrl' as string]  as unknown as any,
	supportEmail: window['env' as any]['supportEmail' as any] as unknown as string,
	isAuthBypassed: window['env' as any]['isAuthBypassed'] as unknown as any,
	password: window['env' as any]['password']  as unknown as any
}

// export const environment = {
//   production: false,
//   name: 'debug environment',
//   staging: false,
//   dev: false,
//   baseUrl: 'https://dev.elevate-apis.shikshalokam.org',
//   sqliteDBName: 'mentoring.db',
//   deepLinkUrl: 'https://mentored.shikshalokam.org',
//   privacyPolicyUrl:'https://shikshalokam.org/mentoring/privacy-policy',
//   termsOfServiceUrl:'https://shikshalokam.org/mentoring/term-of-use',
//   chatBaseUrl:'https://chat-dev.elevate-apis.shikshalokam.org',
//   chatWebSocketUrl :'wss://chat-dev.elevate-apis.shikshalokam.org/websocket',
//   supportEmail: "mentoredtest1@yopmail.com",
//   // recaptchaSiteKey:"6LfWEKYpAAAAACxKbR7H42o3BwbJkJA06vIM_6Ea",
//   recaptchaSiteKey:"",
//   restictedPages: [],
//   isAuthBypassed: false,
//   unauthorizedRedirectUrl: "/auth/login",
//   password:{
//     minLength:10,
//     regexPattern:"^(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#%$&()\\-`.+,/]).{10,}$",
//     errorMessage:"Password should contain at least one uppercase letter, one number and one special character."
//   },
// };
	// production: false ,
	// name: window['env' as any]['name' as any] ,
	// baseUrl: window['env' as any]['baseUrl'] ,
	// sqliteDBName: window['env' as any]['sqliteDBName' as any] ,
	// deepLinkUrl: window['env' as any]['deepLinkUrl'],
	// privacyPolicyUrl: window['env' as any]['privacyPolicyUrl' as any] ,
	// termsOfServiceUrl: window['env' as any]['termsOfServiceUrl' as any] ,
	// recaptchaSiteKey: window['env' as any]['recaptchaSiteKey'] ,
	// recaptchaSiteKeyOld: window['env' as any]['recaptchaSiteKeyOld' as any] ,
	// restictedPages: window['env' as any]['restictedPages'],
	// unauthorizedRedirectUrl: window['env' as any]['unauthorizedRedirectUrl' as string] ,
	// supportEmail: window['env' as any]['supportEmail' as any] ,
	// isAuthBypassed: window['env' as any]['isAuthBypassed'] ,
	// password: window['env' as any]['password'] 

