import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LineElement } from 'chart.js/dist';
import { CommonRoutes } from 'src/global.routes';

@Component({
  selector: 'app-manage-session',
  templateUrl: './manage-session.component.html',
  styleUrls: ['./manage-session.component.scss'],
})
export class ManageSessionComponent implements OnInit {
  tableData:any;
  public headerConfig: any = {
    menu: true,
    notification: true,
    headerColor: 'primary',
    label:'MANAGE_SESSION'
  };
  constructor(private router: Router) { }
  columnData = [
    {name:'no',displayName:'No.', sorting:false, sortingData:"dont know as of now"},
    {name:'sessionName', displayName:'Session name',sorting:true, sortingData:"dont know as of now"},
    {name:'type', displayName:'Type',sorting:false, sortingData:"dont know as of now"},
    {name:'mentor',displayName:'Mentor', sorting:false, sortingData:"dont know as of now"},
    {name:'date',displayName:'Date', sorting:true, sortingData:"dont know as of now"},
    {name:'time', displayName:'Time',sorting:true, sortingData:"dont know as of now"},
    {name:'duration',displayName:'Duration(min)', sorting:true, sortingData:"dont know as of now"},
    {name:'menteeCount', displayName:'Mentee count',sorting:false, sortingData:"dont know as of now"},
    {name:'status',displayName:'Status', sorting:false, sortingData:"dont know as of now"},
    {name:'action', displayName:'Actions',sorting:false, sortingData:"dont know as of now"},
]

  ngOnInit() {
    this.tableData = [
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      }, { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
       { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      }, { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 1, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
      { "no": 10, 
      "sessionName": 'Micro improvements-1',
       "type": 'private' ,
       "mentor": 'Meno"tr name',
       "date": '12-10-1014',
       "time":'10:30',
       "duration":60,
       "menteeCount":25,
       "status":'live',
       "action":'live'
      },
       
      // Add more data as needed
     
    ];
  }

  createSession(){
    this.router.navigate([`${CommonRoutes.ADMIN}/${CommonRoutes.MANAGERS_SESSION}`]);
  }

}
